env-files: [ "env1.csv", "env2.csv"] # List of environment files
model-paths: ["env_model1", "env_model2"] # List of model paths, Note: name like "env_scenario<idx>_<idx2>" is used in the code
trainEnv